permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "IGeek-Feng"
email: "845882161@163.com"
description: "To make each day count"
#让每一天都有所值。
github_username:  "webweifeng"





url: "https://webweifeng.github.io"
imgrepo: "https://webweifeng.github.io/igeek.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

