# Version of the Icarus theme that is currently used
version: 2.6.0
# Path or URL to the website's icon
favicon: /images/favicon.ico
# Additional HTML meta tags in an array.
meta:
# Path or URL to RSS atom.xml
rss: /atom.xml

# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
logo:
  text: QIAO
# Open Graph metadata
# https://hexo.io/docs/helpers.html#open-graph
open_graph:
  # Facebook App ID
  fb_app_id:
  # Facebook Admin ID
  fb_admins:
  # Twitter ID
  twitter_id:
  # Twitter site
  twitter_site:
  # Google+ profile link
  google_plus:
# Navigation bar link settings
navbar:
  # Navigation bar menu links
  menu:
    首页: /
    归档: /archives
    类目: /categories
    Tags: /tags
    图床: http://img.v5ant.com
    在线影视: http://mv.v5ant.com
    优惠券: http://tao.v5ant.com
    关于: /about
  # Navigation bar links to be shown on the right
  links:
    My GitHub:
      icon: fa fa-github
      url: 'https://github.com/webweifeng'
# Footer section link settings
footer:
  # Links to be shown on the right of the footer section
  links:
    Creative Commons:
      icon: fa fa-creative-commons
      url: 'https://creativecommons.org/'
    # Attribution 4.0 International:
    #   icon: fa fa-creative-commons-by
    #   url: 'https://creativecommons.org/licenses/by/4.0/'
    Download on GitHub:
      icon: fa fa-github
      url: 'https://github.com/ppoffice/hexo-theme-icarus'
# Article display settings
article:
  # Code highlight settings
  highlight:
    # Code highlight themes
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    theme: monokai-sublime
    # Show code copying button
    clipboard: true
    # Default folding status of the code blocks. Can be "", "folded", "unfolded"
    fold: unfolded
  # Whether to show article thumbnail images
  thumbnail: true
  # Whether to show estimate article reading time
  readtime: true
# Search plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search
search:
  # Name of the search plugin
  type: insight
# Comment plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment
comment:
  # Name of the comment plugin
  # Donation entries
  # https://ppoffice.github.io/hexo-theme-icarus/categories/Donation/
  type: valine
  app_id: 0dRsbpsRF1nGv05qtTfG3yaO-gzGzoHsz # (required) LeanCloud application id
  app_key: vYOmHvLIqyDY1AgnpdxDrM8E # (required) LeanCloud application key
  notify: false # (optional) receive email notification
  verify: false # (optional) show verification code
  placeholder: just so so # (optional) comment box placeholder text
donate:
  - # Donation entry name
    type: alipay
    # Qrcode image URL
    qrcode: '/images/alipay_qrcode.png'
  - # Donation entry name
    type: wechat
    # Qrcode image URL
    qrcode: '/images/wxpay_qrcode.png'
    # Donation entry name
    # type: paypal
    # Paypal business ID or email address
    # business: ''
    # Currency code
    currency_code: USD
  # - Donation entry name
  # type: patreon
  # URL to the Patreon page
  # url: ''
# Share plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share
share:
  # Share plugin name
  type: sharethis
  install_url: https://platform-api.sharethis.com/js/sharethis.js#property=5d788e15ab6f1000123c87c4&product=inline-share-buttons
# Sidebar settings.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
  # left sidebar settings
  left:
    # Whether the left sidebar is sticky when page scrolls
    # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
    sticky: true
  # right sidebar settings
  right:
    # Whether the right sidebar is sticky when page scrolls
    # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
    sticky: true
# Sidebar widget settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
  - # Widget name
    type: profile
    # Where should the widget be placed, left or right
    position: left
    # Author name to be shown in the profile widget
    author: QiaoJianFeng
    # Title of the author to be shown in the profile widget
    author_title: Before you quit,Try
    # Author's current location to be shown in the profile widget
    location: ShanXi-DaTong
    # Path or URL to the avatar to be shown in the profile widget
    avatar: /images/avatar.png
    # Email address for the Gravatar to be shown in the profile widget
    gravatar:
    # Whether to show avatar image rounded or square
    avatar_rounded: true
    # Path or URL for the follow button
    follow_link: 'https://github.com/webweifeng'
    # Links to be shown on the bottom of the profile widget
    social_links:
      Github:
        icon: fa fa-github
        url: 'https://github.com/webweifeng'
      影视:
        icon: fa fa-youtube-play
        url: 'https://www.imov.vip'
      QQ:
        icon: fa fa-qq
        url: 'tencent://message/?uin=845882161&Site=蚂蚁号&Menu=yes'
      留言:
        icon: fa fa-comments
        url: '/message'
      RSS:
        icon: fa fa-rss
        url: /
  - # Widget name
    type: toc
    # Where should the widget be placed, left or right
    position: left
  - # Widget name
    type: links
    # Where should the widget be placed, left or right
    position: left
    # Links to be shown in the links widget
    links:
      蚂蚁影视: 'http://mv.v5ant.com'
  - # Widget name
    type: category
    # Where should the widget be placed, left or right
    position: left
  - # Widget name
    type: tagcloud
    # Where should the widget be placed, left or right
    position: left
  - # Widget name (广告小部件)
    type: ads
    # Where should the widget be placed, left or right
    position: right
    # 广告图片
    adImg: /images/ad1.png
  - # Widget name
    type: recent_posts
    # Where should the widget be placed, left or right
    position: right
  - # Widget name
    type: archive
    # Where should the widget be placed, left or right
    position: right
  - # Widget name
    type: tag
    # Where should the widget be placed, left or right
    position: right
# Other plugin settings
plugins:
  # Enable page animations
  animejs: true
  # Enable the lightGallery and Justified Gallery plugins
  # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
  gallery: true
  # Enable the Outdated Browser plugin
  # http://outdatedbrowser.com/
  outdated-browser: true
  # Enable the MathJax plugin
  # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/mathjax-plugin/
  mathjax: true
  # Show the back to top button on mobile devices
  back-to-top: true
  # Google Analytics plugin settings
  # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Google-Analytics
  google-analytics:
    # Google Analytics tracking id
    tracking_id:
  # Baidu Analytics plugin settings
  # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Baidu-Analytics
  baidu-analytics:
    # Baidu Analytics tracking id
    tracking_id:
  # Hotjar user feedback plugin
  # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Hotjar
  hotjar:
    # Hotjar site id
    site_id:
  # Show a loading progress bar at top of the page
  progressbar: true
  # BuSuanZi site/page view counter
  # https://busuanzi.ibruce.info
  busuanzi: true
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
  # Name or URL of the JavaScript and/or stylesheet CDN provider
  cdn: jsdelivr
  # Name or URL of the webfont CDN provider
  fontcdn: google
  # Name or URL of the webfont Icon CDN provider
  iconcdn: fontawesome
copyright:
  enable: true
  img: http://ostu98x74.bkt.clouddn.com/copyright/copyright.png #版权信息图片
  site: https://q-jf.cn
  siteName: QIAOの博客
  siteAuthor: 'JF · Qiao'
